name: build
concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || (github.ref == 'refs/heads/main' && github.sha) || github.ref }}
    cancel-in-progress: true
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 8
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '8'
            - name: Build
              run: mvn --batch-mode clean package
    liquibase-compatibility:
        runs-on: ubuntu-latest
        needs: build
        strategy:
            matrix:
                liquibase-version:
                    - '[3.4.0,3.5.0)'
                    - '[3.5.0,3.6.0)'
#                    - '[3.6.0,3.7.0)'
#                    - '[3.7.0,3.8.0)'
                include:
                    -   liquibase-version: '[3.4.0,3.5.0)'
                        yaml-version: '1.13'
                    -   liquibase-version: '[3.5.0,3.6.0)'
                        yaml-version: '1.17'
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 8
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: '8'
            - name: Run Liquibase compatibility tests for liquibase version ${{ matrix.liquibase-version }}
              run: mvn clean test --batch-mode -Dliquibase.version="${{ matrix.liquibase-version }}" -Dyaml.version="${{ matrix.yaml-version }}"
