name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    if: github.repository == 'liquibase-linter/liquibase-linter'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
